# Generated by Django 6.0 on 2025-12-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={},
        ),
    ]
